
### Get All customers
GET http://localhost:8082/api/customers


### Get a customer by ID
GET http://localhost:8082/api/customers/1


### Add a customer
POST http://localhost:8082/api/customers
Content-Type: application/json

{
  "name": "Customer",
  "email": "customer@gmail.com",
  "phone": "12345678",
  "address": "Tartu, Estonia"
}

### Update a customer
PUT http://localhost:8082/api/customers/1
Content-Type: application/json

{
  "name": "Good Customer",
  "email": "customer@gmail.com",
  "phone": "12345678",
  "address": "Tallinn, Estonia"
}

### Delete a customer
DELETE http://localhost:8082/api/customers/1


